[findseq]
config = "positional"
read1_filename = "optional"
read2_filename = "optional"
output_filename = "optional"
fastqfiles = "optional"
outdir = "optional"

[collapse]
input_file = "optional"
input_dir = "optional"
output_file = "optional"
output_dir = "optional"
columns = "required"
mismatches = 2
sep = ","
row_limit = "optional"
method = "directional"
metrics = "optional"
config = "optional"

[count]
input_file = "optional"
input_dir = "optional"
output_file = "optional"
output_dir = "optional"
barcode_column = "required"
key_column = "required"
sep = ","
row_limit = "optional"
allowed_list = "optional"
detailed = false
downsample = "optional"
random_seed = "optional"
metrics = "optional"
config = "optional"

[gini]
input_file = "positional"
column = "required"
count_column = "optional"
scale = "optional"
sep = ","
allowed_list = "optional"
config = "optional"

[visualize]
input_dir = "positional"
output_dir = "positional"
sep = ","
bins = 50
title_prefix = "optional"
xlabel = "optional"
ylabel = "optional"
log_scale = false
format = "png"

[pipeline]
config_file = "positional"
snakemake_config = "positional"
snakemake_args = "optional"
